output_dir: ~/experiments/

dataset:
  class: Road
  path: ~/Desktop/NBFNET-SSP/data
  name: auth_small
  random_weights: no

task:
  class: PredecessorPrediction
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32]
    message_func: add
    aggregate_func: min
    short_cut: no
    layer_norm: no
    dependent: no
    remove_one_hop: no
    symmetric: no
    num_nodes: 278
    num_iterations: 20
    recover: no
  criterion: ce

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 1

train:
  num_epoch: 10

metric: accuracy