output_dir: ~/experiments/

dataset:
  class: Road
  path: ~/Desktop/NBFNET-SSP/data
  name: evag
  random_weights: no

task:
  class: PredecessorPrediction
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32]
    message_func: add
    aggregate_func: min
    short_cut: no
    layer_norm: no
    dependent: no
    remove_one_hop: no
    symmetric: no
    num_nodes: 45
    num_iterations: 30
    recover: yes
  criterion: ce

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 1

checkpoint: {{ checkpoint }}

metric: accuracy

data:
 name: evag
 bounding_box:
   xlow: 22.9572
   xhigh: 22.9623
   ylow: 40.6334
   yhigh: 40.6365
 threshold: 0
