output_dir: ~/experiments/

dataset:
  class: Road
  path: ~/Desktop/NBFNET-SSP11/data
  name: lagadas_small
  random_weights: no

task:
  class: PredecessorPrediction
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32,32]
    message_func: add
    aggregate_func: min
    short_cut: no
    layer_norm: no
    dependent: no
    remove_one_hop: no
    symmetric: no
    num_nodes: 78
    num_iterations: 4
    recover: yes
  criterion: ce

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 4

checkpoint: {{ checkpoint }}

metric: accuracy

data:
 name: lagadas_small
 bounding_box:
  xlow: 23.06445
  xhigh: 23.07061
  ylow: 40.74854
  yhigh: 40.75219
 threshold: 800