output_dir: ~/experiments/

dataset:
  class: Road
  path: /home/spyridod/Desktop/NBFNET-SSP11/data
  name: lagadas_extra_small
  random_weights: no

task:
  class: PredecessorPrediction
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32]
    message_func: add
    aggregate_func: min
    short_cut: no
    layer_norm: no
    dependent: no
    remove_one_hop: no
    symmetric: no
    num_nodes: 21
    num_iterations: 4
  criterion: ce

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 16

train:
  num_epoch: 400


metric: accuracy